[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
rayon = { workspace = true }
uuid = { workspace = true }

node = { workspace = true }
plugin = { workspace = true }

matcha = { workspace = true }
